package com.kompu.api.usecase.auth.dto;

import java.util.Map;
import java.util.UUID;

/**
 * DTO interface for user registration request
 * 
 * Framework-independent contract for sign-up operations.
 * This interface is defined in the Use Case layer and should not have any
 * Spring or validation framework dependencies.
 * 
 * Implementations of this interface should be in the Infrastructure layer
 * with proper validation annotations.
 * 
 * Maps to schema entities:
 * - app.users (username, email, password_hash, full_name, phone, avatar_url)
 * - app.members (member_code, full_name, email, phone, address, joined_at)
 * - app.tenants (name, code, status, metadata)
 * - app.roles (assigned via role name)
 * - app.permissions (inherited from assigned role)
 */
public interface ISignUpRequest {

    // ===== User Account Fields (from app.users) =====

    /**
     * Username for authentication (3-50 chars, unique per tenant)
     */
    String username();

    /**
     * Email address (unique per tenant)
     */
    String email();

    /**
     * Plain-text password (will be hashed)
     */
    String password();

    /**
     * Password confirmation (must match password)
     */
    String confirmPassword();

    /**
     * Full name of the user
     */
    String fullName();

    /**
     * Optional phone number of the user
     */
    String phone();

    /**
     * Optional avatar URL or file path for profile picture
     * For multipart uploads, provide URL after file is stored
     */
    String avatarUrl();

    // ===== Tenant Context =====

    /**
     * Optional tenant ID for joining existing tenant.
     * If null, a new tenant will be created for the user as Admin.
     * If provided, user joins as Member.
     * 
     * @return the tenant ID, or null to create new tenant
     */
    UUID tenantId();

    /**
     * Optional tenant name (used when creating new tenant).
     * If null, generated from username or other logic.
     */
    String tenantName();

    /**
     * Optional tenant code/slug (used when creating new tenant).
     * If null, generated from username (lowercase).
     */
    String tenantCode();

    /**
     * Optional tenant metadata as JSON string.
     * Stored in app.tenants.metadata JSONB field.
     */
    Map<String, Object> tenantMetadata();

    // ===== Member/Employee Fields (from app.members) =====

    /**
     * Optional member code (e.g., "MEM001", "EMP2025001").
     * If null, auto-generated by system.
     */
    String memberCode();

    /**
     * Optional physical address of the member
     */
    String address();

    /**
     * Optional additional member metadata as JSON string.
     * Stored in app.members.metadata JSONB field.
     */
    String memberMetadata();

    // ===== Role Assignment =====

    /**
     * Optional explicit role name for assignment.
     * If null:
     * - For new tenant: "Admin" role assigned
     * - For existing tenant: "Member" role assigned
     * 
     * @return role name, or null for default role assignment
     */
    String roleName();

}
